// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCRVTrackCursorInfo wrapper class

class CCRVTrackCursorInfo : public COleDispatchDriver
{
public:
	CCRVTrackCursorInfo() {}		// Calls COleDispatchDriver default constructor
	CCRVTrackCursorInfo(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCRVTrackCursorInfo(const CCRVTrackCursorInfo& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetDetailAreaCursor();
	void SetDetailAreaCursor(long nNewValue);
	long GetDetailAreaFieldCursor();
	void SetDetailAreaFieldCursor(long nNewValue);
	long GetGraphCursor();
	void SetGraphCursor(long nNewValue);
	long GetGroupAreaCursor();
	void SetGroupAreaCursor(long nNewValue);
	long GetGroupAreaFieldCursor();
	void SetGroupAreaFieldCursor(long nNewValue);
};
