//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by diagramx.rc
//
#define IDUSUREFRESCA                   3
#define IDC_FORMATO                     3
#define IDR_DSVXTYPE_SRVR_IP            4
#define IDR_DSVXTYPE_SRVR_EMB           5
#define IDR_DSVXTYPE_CNTR_IP            6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_AVISO_GRIDMUERE              106
#define ID_AVISO_DEFIMPRE               107
#define ID_AVISO_GRIDPOSICIONA          108
#define ID_AVISO_GRIDRELLENA            109
#define ID_AVISO_GRIDLOCALEDITA         110
#define ID_AVISO_POSTGRIDPOSICIONA      111
#define ID_AVISO_MUEREMETA              112
#define ID_AVISO_PREDETERMINADO         113
#define ID_AVISO_INVALIDATE_GRID        114
#define ID_TTOOLMENU                    115
#define ID_TTOOLMAIN                    116
#define ID_AVISO_EDITAFILTRO            117
#define ID_AVISO_POSTGRIDENSUREVISIBLE  118
#define ID_AVISO_DOUBLECLICK            119
#define ID_GRID_DELETE_OBJECT           120
#define ID_GRID_POSICION                121
#define ID_GRIDENDLABELEDIT             122
#define ID_GRIDNUEVACOLUMNA             123
#define IDR_MAINMENU                    127
#define IDR_MAINFRAME                   127
#define IDR_TOOLMAINFRAME               128
#define IDR_DSXTYPE                     129
#define IDR_HTMLVIEW                    130
#define IDD_LOGIN                       131
#define IDB_TREESEL                     135
#define IDB_TREEOPEN                    136
#define IDB_TREEFIL                     137
#define IDB_TREEFOL                     138
#define IDR_CNTR_INPLACE                139
#define IDD_DIALOGOIMPRE                146
#define IDD_KACTIVACION                 147
#define IDD_TRASMITE                    149
#define IDD_USUARIOS                    150
#define IDD_MATA                        151
#define IDR_MENUTRAZA                   152
#define IDD_TRAZA_BUSCAR                153
#define IDB_CLAVE                       154
#define IDB_GRIDSEL                     155
#define IDI_INDICATOR                   158
#define IDI_NUEVA                       159
#define IDD_COLORES                     160
#define IDD_GRIDRELLENA                 161
#define IDD_SIONO                       162
#define IDD_ENTRACLAVE                  162
#define IDB_CONSULGRID                  163
#define IDB_BOTGRIDSEL                  164
#define IDB_BOTGRIDNUE                  165
#define IDB_BOTGNUESEL                  166
#define IDD_ERRORFICHERO                168
#define IDD_INDEXADO                    169
#define IDD_MIUSERWEB                   170
#define IDD_ENVIACORREO                 171
#define IDD_DIALOGOOLDIMPRE             172
#define IDD_FILTRO                      173
#define IDD_CAMBIACLAVE                 179
#define IDD_BUSMENU                     180
#define IDD_PROGRESO                    187
#define IDR_TOOLGRID                    188
#define IDR_SRVR_EMBEDDED               191
#define IDR_NAVEGA                      191
#define IDR_SRVR_INPLACE                192
#define IDB_FICHA_NUEVA                 193
#define IDI_FICHA_NUEVA                 194
#define IDB_FICHA_MODIFICAR             197
#define IDB_FICHA_BAJA                  199
#define IDB_FICHA_PRIMERA               200
#define IDB_FICHA_ANTERIOR              201
#define IDB_FICHA_SIGUIENTE             202
#define IDB_FICHA_ULTIMA                203
#define MENSAJE_CABECERA_0              203
#define IDB_FICHA_BUSCAR                204
#define MENSAJE_CABECERA_1              204
#define IDB_FICHA_IMPRIMIR              205
#define MENSAJE_CABECERA_2              205
#define MENSAJE_CABECERA_3              206
#define IDB_FICHA_VALIDAR               206
#define MENSAJE_CABECERA_4              207
#define IDB_FICHA_CANCELAR              207
#define IDB_OTRO                        208
#define IDR_ION2                        209
#define IDR_TOOLMENSA                   212
#define IDD_NEWPASSWD                   213
#define IDD_COLUMNAS                    214
#define IDD_SOPORTE                     216
#define IDB_PUNTO_ROJO                  217
#define IDB_PUNTO_AMARILLO              218
#define IDB_PUNTO_VERDE                 219
#define IDD_EXPORTAGRID                 220
#define ID_NUEVAPOSICIONGRID            221
#define IDD_BROWSE                      222
#define IDB_TICSCON                     223
#define IDB_TICSCON1                    224
#define IDB_TICSCON2                    225
#define IDD_NUEVARELA                   226
#define IDB_FLECHAI                     227
#define IDB_FLECHAD                     228
#define IDB_DFLECHAI                    229
#define IDB_DFLECHAD                    230
#define IDR_TOOLBARMENU                 233
#define IDR_TOOLBARMENU1                234
#define IDR_TOOLMAINFRAME1              235
#define IDR_TOOLGRID1                   236
#define IDD_DIALOGCALENDAR              237
#define IDR_MAINFRAME1                  237
#define IDD_ORDENAR                     238
#define IDD_BUSCAR                      239
#define IDD_OPERACIONES                 240
#define IDR_MENU1                       241
#define IDD_EMBEDDABLE_DESIGNER_DIALOG  242
#define IDC_NEW_REPORT                  243
#define IDC_CRVIEWER1                   244
#define IDC_OPEN_REPORT                 245
#define IDC_SAVE_REPORT                 246
#define IDC_PREVIEW                     247
#define IDC_SHOW_DESIGNER               248
#define IDC_EMBEDDABLECRYSTALREPORTSDESIGNERCTRL1 249
#define IDC_PRINTER                     250
#define IDC_ACTIVEXREPORTVIEWER1        251
#define IDC_MAPI                        252
#define IDB_MAIL                        253
#define IDR_MENU2                       254
#define IDR_SKIN1                       262
#define IDD_DIALOGCAMBIO                263
#define IDC_ACTIVEXREPORTVIEWER2        264
#define IDC_USUARIO                     400
#define IDC_PASSWORD                    401
#define IDC_PASSWORD2                   402
#define IDC_PASSWORD3                   403
#define IDC_IMPREFONT                   404
#define IDC_MARGENI                     405
#define IDC_MARGENS                     406
#define IDC_IMPREAJUSTA                 407
#define IDC_IMPRELINEAS                 408
#define IDC_IMPRECOLS                   409
#define IDC_EXCELCABECERA               410
#define IDC_POSEXCEL                    411
#define IDC_ANIMATEX                    412
#define IDC_MARGENI2                    412
#define IDC_FAXAUTOMATICO               413
#define IDC_NUMEROFAX                   414
#define IDC_CORREOFAX                   415
#define IDC_MIVERSION                   416
#define IDC_CORREOASUNTO                416
#define IDC_TAQUI                       417
#define IDC_MIVERSION0                  417
#define IDC_COPIAS                      417
#define IDC_TALLI                       418
#define IDC_MIVERSION1                  418
#define IDC_DESDEPG                     418
#define IDC_TPROGRESS                   419
#define IDC_HASTAPG                     419
#define IDC_TPASO                       420
#define IDC_DOBLEHOJA                   420
#define IDC_LISTUSERS                   421
#define IDC_SELIMPRECRISTAL             421
#define IDC_CLAVEMATA                   422
#define IDC_TRAZA_ABUSCAR               423
#define IDC_LIST2                       425
#define IDC_S_COLORCONSULTA             426
#define IDC_BUTTON1                     427
#define IDC_BUTTON2                     428
#define IDC_S_COLORSELECCION            429
#define IDC_ANIMATE1                    430
#define IDC_EDIT1                       431
#define IDC_LACLAVE                     431
#define IDC_EDIT2                       432
#define IDC_LACLAVE2                    432
#define IDC_EDIT3                       433
#define IDC_ACTIVACION                  434
#define IDC_EDIT4                       434
#define IDC_IDENTIFICA                  435
#define IDC_NUMERO                      436
#define IDC_TELEFONOS                   437
#define IDC_COMBO1                      438
#define IDC_LISTAOLDIMPRE               439
#define IDC_COMBO2                      439
#define IDC_SPOOLOLDIMPRE               440
#define IDC_LUEGOPOR2                   440
#define IDC_LAIMPRE                     442
#define IDC_TAB2                        443
#define IDC_LIST3                       444
#define IDC_LIST4                       445
#define IDC_RADIO2                      447
#define IDC_RADIOEXACTO                 447
#define IDC_RADIOPREDER                 447
#define IDC_RADIO3                      448
#define IDC_RADIOPARCIAL                448
#define IDC_RADIONOABRIR                448
#define IDC_TAB3                        449
#define IDC_RADIO4                      449
#define IDC_RADIOCONTENIDO              449
#define IDC_RADIOESPE                   449
#define IDC_RADIOEXCEL                  450
#define IDC_RADIO5                      450
#define IDC_RADIOCRYSTAL                451
#define IDC_RADIO6                      451
#define IDC_RADIOCRYSTAL2               452
#define IDC_LIST1                       454
#define IDC_CHECK2                      455
#define IDC_CHECK3                      456
#define IDC_CHECK4                      457
#define IDC_CHECK5                      458
#define IDC_EDIT5                       459
#define IDC_CHECK6                      459
#define IDC_BUTTONGUARDAR               460
#define IDC_CHECK7                      461
#define IDC_FNOMCAMPO                   462
#define IDC_CHECK8                      463
#define IDC_LACLAVE3                    464
#define IDC_BUTTONBORRAR                464
#define IDC_TBUSCAMENU                  465
#define IDC_PROGRESO                    467
#define IDC_SINORDEN                    468
#define IDC_ASCENDENTE                  469
#define IDC_CHECK1                      469
#define IDC_DESCENDENTE                 470
#define IDC_IMPREOEM                    470
#define IDC_SELIMPRE                    471
#define IDC_IMPREWINDOWS                472
#define IDC_CAMBIO                      473
#define IDC_TREE1                       474
#define IDC_NUEVARELACION               475
#define IDC_RADIODBF                    476
#define IDC_RADIOPDB                    477
#define IDC_CHECKBORRAR                 478
#define IDC_DESTINO                     479
#define IDC_PROGRAMA                    480
#define IDC_BUTTONESPE                  481
#define IDC_BUTTONDESTINO               482
#define IDC_PRECRYSTAL                  483
#define IDC_SELE                        484
#define IDC_PRECRYSTAL2                 484
#define IDC_FICHEROS                    486
#define IDC_CAMPOSO                     487
#define IDC_CAMPOSD                     488
#define IDC_RELA                        489
#define IDC_AGRU                        490
#define IDC_CONDAGRU                    491
#define IDC_BUTTON3                     492
#define IDC_PREGUNTAR                   493
#define IDC_COMBOOPERA                  494
#define IDC_COMBOCABECERA               495
#define IDC_CHECKINCLUIDO               496
#define IDC_ORDENCLAVE                  497
#define IDC_LABEL                       498
#define IDC_LABEL_USUARIO               498
#define IDC_LABEL_PASSWORD              499
#define IDC_COPYRIGHT                   500
#define IDC_MONTHCALENDAR1              501
#define IDC_CONTROLBUILD                502
#define IDC_ARRIBA                      503
#define IDC_MACADDRESS                  503
#define IDC_ABAJO                       504
#define IDC_MAXIMO                      504
#define IDC_BAJAR                       505
#define IDC_MINIMO                      505
#define IDC_SUBIR                       506
#define IDC_SUMA                        506
#define IDC_DES2                        507
#define IDC_ASC3                        508
#define IDC_DES3                        509
#define IDC_ORDENARPOR                  510
#define IDC_LUEGOPOR                    511
#define IDC_BUSCAREN                    512
#define IDC_ASC1                        513
#define IDC_DES1                        514
#define IDC_ASC2                        515
#define IDC_STATIC1                     516
#define IDC_STATIC2                     517
#define IDC_STATIC3                     518
#define IDC_STATIC4                     519
#define IDC_STATIC5                     520
#define IDC_STATIC6                     521
#define IDC_STATIC7                     522
#define IDC_STATIC8                     523
#define IDC_STATIC9                     524
#define IDC_STATIC10                    525
#define IDC_XRADIOEXACTO                526
#define IDC_STATIC11                    526
#define IDC_STATIC12                    527
#define IDC_STATIC53                    528
#define IDC_STATIC10a                   529
#define IDC_STATIC14                    529
#define IDC_STATIC10b                   530
#define IDC_STATIC17                    532
#define IDC_RADIO1                      533
#define IDC_STATIC18                    533
#define IDC_DATETIMEPICKER1             534
#define IDC_STATIC19                    534
#define IDC_DATETIMEPICKER2             535
#define IDC_STATICNEUTRO                536
#define IDC_STATIC50                    537
#define IDC_STATIC51                    538
#define IDC_STATIC52                    539
#define IDC_STATIC54                    540
#define IDC_STATIC55                    541
#define IDC_STATIC56                    542
#define IDC_STATIC57                    543
#define IDC_STATIC58                    544
#define IDC_STATIC59                    545
#define IDC_HORADESDE                   546
#define IDC_HORAHASTA                   547
#define IDW_WGRID                       550
#define IDW_GRID                        650
#define IDW_WINSYS                      777
#define IDW_EDIT                        790
#define ID_TECLAVALIDA                  801
#define ID_RELACION                     820
#define ID_CLAVES                       821
#define ID_MIAYUDA                      822
#define ID_ALT_DOWN                     992
#define ID_ALT_UP                       994
#define ID_RESIZABLE_BAR                995
#define MID_MENUSG                      1000
#define MID_DISENO                      1100
#define IDW_STDDLG                      3000
#define DESPACHO_OMENU                  4001
#define DESPACHO_EMENU                  4002
#define DESPACHO_PANTALLAS              4003
#define DESPACHO_TITULO                 4004
#define DESPACHO_MAINCOMMAND            4005
#define NUEVA_TECLA_PROGRAMADA          4006
#define DESPACHO_EN_LINEAS              4007
#define DESPACHO_MI_CONTROL             4008
#define DESPACHO_FIN_CONTROL            4009
#define DESPACHO_PRE_CONTROL            4010
#define DESPACHO_SOBRE_PANTALLA         4011
#define DESPACHO_REPON_PANTALLA         4012
#define DESPACHO_MENSAJE_CABECERA       4013
#define DESPACHO_FUNCIONES_IMPRESION    4014
#define DESPACHO_BOTONSALIDA            4015
#define DESPACHO_COMMANDCONTROL         4016
#define DESPACHO_TRASMISION             4017
#define DESPACHO_PROGRESO               4018
#define DESPACHO_USUARIOS               4019
#define DESPACHO_INICIO_TRAZA           4020
#define DESPACHO_FIN_TRAZA              4021
#define DESPACHO_PUNTO_TRAZA            4022
#define DESPACHO_BINARIO                4023
#define DESPACHO_PROCESAMENSAJES        4024
#define DESPACHO_CCONTROL               4025
#define DESPACHO_CEDIT                  4026
#define DESPACHO_GETDATACONTROL         4027
#define DESPACHO_FOCOCONTROL            4028
#define DESPACHO_DESTRUYECONTROL        4029
#define DESPACHO_REFRESCACONTROL        4030
#define DESPACHO_FOCOWINDOW             4031
#define DESPACHO_TRAEFICHERO            4032
#define DESPACHO_ENLACEWORD             4033
#define DESPACHO_LISTADO                4034
#define DESPACHO_BROWSE                 4035
#define DESPACHO_ESTADOCONTROL          4036
#define DESPACHO_EURO                   4037
#define DESPACHO_SUPERUSUARIO           4038
#define DESPACHO_MENUITEM               4039
#define DESPACHO_CONSULTA_REMOTA        4040
#define DESPACHO_MULTIPLE               4041
#define DESPACHO_DIF_CCONTROL           4042
#define DESPACHO_DIF_CEDIT              4043
#define DESPACHO_DIF_FOCOCONTROL        4044
#define DESPACHO_DATA_PROCESAMENSAJES   4045
#define DESPACHO_DATA_INFO              4046
#define IDC_DSCOMBO_BUTTON              4317
#define IDC_DSCOMBO_EDIT                4318
#define IDC_DSCOMBO_LIST                4319
#define DESPACHO9_OMENU                 4501
#define DESPACHO9_EMENU                 4502
#define DESPACHO9_PANTALLAS             4503
#define DESPACHO9_TITULO                4504
#define DESPACHO9_QUEPANTALLA           4505
#define NUEVA9_TECLA_PROGRAMADA         4506
#define DESPACHO9_EN_LINEAS             4507
#define DESPACHO9_MI_CONTROL            4508
#define DESPACHO9_FIN_CONTROL           4509
#define ID_HTMLNAVEGAHOME               4509
#define DESPACHO9_PRE_CONTROL           4510
#define DESPACHO9_SOBRE_PANTALLA        4511
#define DESPACHO9_REPON_PANTALLA        4512
#define DESPACHO9_MENSAJE_CABECERA      4513
#define DESPACHO9_FUNCIONES_IMPRESION   4514
#define DESPACHO9_HAZ_VISIBLE           4515
#define DESPACHO9_EDITA                 4516
#define DESPACHO9_TRASMISION            4517
#define DESPACHO9_PROGRESO              4518
#define DESPACHO9_USUARIOS              4519
#define DESPACHO9_INICIO_TRAZA          4520
#define DESPACHO9_FIN_TRAZA             4521
#define DESPACHO9_PUNTO_TRAZA           4522
#define DESPACHO9_BINARIO               4523
#define DESPACHO9_PRETRANSLATE          4524
#define DESPACHO9_TRAEFICHERO           4532
#define DESPACHO9_ENLACEWORD            4533
#define DESPACHO9_BROWSE                4535
#define DESPACHO9_ESTADOCONTROL         4536
#define DESPACHO9_EURO                  4537
#define DESPACHO9_SUPERUSUARIO          4538
#define SCROLLBAR_DE_LINEAS             5555
#define ID_TRAZAEDIT                    6666
#define ID_TRAZAVAR                     6667
#define ID_TRAZASINBOLFIN               6700
#define ID_REAJUSTASCROLL               7999
#define MID_XPRIMERA                    8000
#define MID_XOPCION1                    30001
#define MID_ACTUALIZAMENU               30996
#define MID_XCLIPCOPY                   30997
#define MID_XCLIPPASTE                  30998
#define MID_XACERCA                     30999
#define MID_MITAB                       31000
#define MID_MIDSWIN                     31100
#define MID_ACTUALIZA_AREA              31200
#define SOBREPONE_PANTALLA              31201
#define REPON_PANTALLA                  31202
#define ACTIVA_NUEVO_ENTORNO            31203
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_BUTTON32777                  32777
#define ID_BUTTON32778                  32778
#define ID_TOOLFUNCION                  32779
#define ID_BUTTON32780                  32780
#define ID_TOOLIR                       32780
#define ID_EDITAR_CANCELAR              32784
#define ID_VIEW_TREE                    32785
#define ID_AJUSTASIZE                   32786
#define ID_OTROSFONTS                   32787
#define ID_FONTMENSA                    32788
#define ID_FONTBOTOM                    32789
#define ID_FONTAUTO                     32790
#define ID_FONTTEXTO                    32791
#define ID_FONTINTEN                    32792
#define ID_FONTDEFAULT                  32793
#define ID_IMPRESORAINTERNA             32794
#define ID_VERTREEMENU                  32795
#define ID_IMPREDATOS                   32797
#define ID_IMPREXCEL                    32798
#define ID_CENTRAR                      32799
#define ID_SINGLEEXPAND                 32800
#define ID_MULTITAREA                   32801
#define ID_TRASMITIR                    32802
#define ID_USERLIST                     32804
#define ID_TRAZA_AVANCEUNO              32805
#define ID_TRAZA_AVANCECONTINUO         32806
#define ID_TRAZA_CORRER                 32807
#define ID_TRAZA_ABRIR                  32809
#define ID_TRAZA_TODOSBREAK             32810
#define ID_TRAZA_AVANCESALTO            32811
#define ID_TRAZA_BUSCAR                 32815
#define ID_TRAZA_SIGUIENTE              32816
#define ID_FOCUS_TREE                   32817
#define ID_UNFOCUS_TREE                 32818
#define ID_ACCEL32820                   32820
#define ID_FONTGRID                     32821
#define ID_SETCOLORES                   32822
#define ID_RECORD_UPDATE                32828
#define ID_RECORD_NEW                   32829
#define ID_RECORD_DELETE                32830
#define ID_SIONO                        32831
#define ID_SIONOCANCELAR                32832
#define ID_MESSAGEBOX                   32833
#define ID_PREGUCLAVE                   32834
#define ID_ERRORFICHERO                 32835
#define ID_DLGKACTIVA                   32836
#define ID_DLGINDICES                   32837
#define ID_MENUSER                      32838
#define ID_SIEMPREHTML                  32839
#define ID_FONDOHTML                    32840
#define ID_STARTMYTIMER                 32841
#define ID_FONDOWEB                     32844
#define ID_PTECS                        32845
#define ID_SIGUIENTEPANE                32846
#define ID_ANTERIORPANE                 32847
#define ID_VERCAPTION                   32848
#define ID_IMPREPANTA                   32850
#define ID_EXPORTA_EXCEL                32851
#define ID_EXPORTA_WORD                 32852
#define ID_CREA_FILTRO                  32853
#define ID_CONSULTA_FILTRO              32856
#define ID_GRID_RESTAURA                32857
#define ID_GUARDA_POSICIONES            32858
#define ID_AVISO_GRIDDEFAULTS           32859
#define ID_SIGNAL_PING                  32860
#define ID_CUSTOM_ESTADO                32861
#define ID_COMMANDCONTROL               32862
#define ID_BUSCAMENU                    32864
#define ID_MENUITEM32865                32865
#define ID_9FONTDEFAULT                 32866
#define ID_9FONTAUTO                    32867
#define ID_9AJUSTASIZE                  32868
#define ID_9FONTTEXTO                   32869
#define ID_9OTROSFONTS                  32870
#define ID_9FONTINTEN                   32871
#define ID_9FONTMENSA                   32872
#define ID_9FONTBOTOM                   32873
#define ID_9SETCOLORES                  32874
#define ID_TOOLTIPS                     32875
#define ID_ACTIVAR_CRISTAL              32876
#define ID_SETCOLORES1                  32877
#define ID_SETCOLORES2                  32878
#define ID_SETCOLORES3                  32879
#define ID_SETCOLORES4                  32880
#define ID_SETCOLORES5                  32881
#define ID_LISTATAREAS                  32882
#define ID_TOOLMENSA                    32883
#define ID_9FONTEDITA                   32884
#define ID_VIEW_TOOLGRID                32887
#define ID_TTOOLGRID                    32887
#define ID_VIEW_TOOLWEB                 32888
#define ID_TTOOLWEB                     32888
#define ID_VIEW_TOOLMENSA               32890
#define ID_TTOOLMENSA                   32890
#define ID_CONTROLREMTO                 32892
#define ID_CONSULTA_TODACOLUMNAS        32893
#define ID_GUARDA_POSICIONES2           32894
#define ID_EXPORTA_PLB                  32894
#define ID_EXPORTA_RPT                  32895
#define ID_TICSCON                      32896
#define ID_AVISOGLOBO                   32897
#define ID_EXPORTA_XML                  32899
#define ID_GRIDIMPRIME                  32900
#define ID_IRA                          32901
#define ID_PRUEBA_PRUEBA                32902
#define ID_PRUEBA_P                     32903
#define ID_PRUEBA_PRUEBA32904           32904
#define ID_D                            32905
#define ID_DYNAMIC_BARS_LIST            32907
#define IDD_TOOLBARMENU1                32909
#define IDD_TOOLBARMENU2                32910
#define IDD_TOOLBARMENU3                32911
#define ID_MENU                         32912
#define ID_PESTANA                      32913
#define ID_FLAGCOMMAND                  32914
#define ID_Menu                         32916
#define ID_AJUSTARPANTALLA9_100         32917
#define ID_AJUSTARPANTALLA9_125         32918
#define ID_AJUSTARPANTALLA9_150         32919
#define ID_Menu32920                    32920
#define ID_PANTALLA9_175                32921
#define ID_PANTALLA9_200                32922
#define ID_IDR                          32925
#define ID_ANYTECLA                     32926
#define ID_ASISTENCIA                   32928
#define ID_TESTCRYSTAL                  32929
#define SOLICITA_RETROCESO              -32011
#define SOLICITA_AVANCE                 -32010
#define SOLICITA_ANULACION              -32009
#define SOLICITA_VALIDACION             -32008
#define SOLICITA_SCROLLDOWN             -32007
#define SOLICITA_SCROLLUP               -32006
#define SOLICITA_SUPRESION              -32005
#define SOLICITA_INSERCION              -32004
#define SOLICITA_INICIO                 -32003
#define SOLICITA_FINAL                  -32002
#define SOLICITA_POSICION               -32001
#define ID_ERROR1                       41234
#define ID_ERROR2                       41235
#define ID_ERROR3                       41236
#define IDS_STRINGCABECERA              62446
#define IDS_RELACION                    62447
#define IDS_CLAVES                      62448
#define IDS_MENSACLAVE                  62448
#define IDS_MENSARELA                   62449
#define IDS_USUARIO                     62450
#define DISPARO_CONTROL                 63200
#define MAX_DISPARO_CONTROL             63600
#define PREDISPARO_CONTROL              63600
#define PREMAX_DISPARO_CONTROL          64000
#define BUSCA_PTECS                     64000
#define PIDO_TRASMISION                 64001
#define PIDO_USUARIOS                   64002
#define PIDO_EMPRESA                    64003
#define TECLA_PING                      64004
#define TECLA_COMBO                     64005
#define TECLA_SUPERUSUARIO              64006
#define PIDO_VEREURO                    64007
#define PIDO_SUPERBLOQUEO               64008
#define PIDO_SUPERDESBLOQUEO            64009
#define PIDO_SUPERCAMBIO                64010
#define PIDO_SUPERTODO                  64011
#define PIDO_SUPERDESTODO               64012
#define TECLA_CHECK                     64013
#define TECLA_DOBLECLICK                64014
#define ID_BUSCON                       64015
#define ID_ACTIVAR_ERP                  64016
#define ID_ACTIVAR_EVT                  64017
#define TECLA_HINT                      64018
#define ID_ACTIVAR_EVTPBX               64019
#define ID_ACTIVAR_EVTCRM               64020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        265
#define _APS_NEXT_COMMAND_VALUE         32932
#define _APS_NEXT_CONTROL_VALUE         547
#define _APS_NEXT_SYMED_VALUE           124
#endif
#endif
