#if !defined(AFX_CRDESIGNERCTRL_H__A0C0F2A3_FBEE_4C37_9F4B_306B119F2153__INCLUDED_)
#define AFX_CRDESIGNERCTRL_H__A0C0F2A3_FBEE_4C37_9F4B_306B119F2153__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCRDesignerCtrl wrapper class

class CCRDesignerCtrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCRDesignerCtrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2a3a1c00, 0xf9db, 0x11d3, { 0x80, 0x8e, 0x0, 0xa0, 0xc9, 0xda, 0xc8, 0x3f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL GetDisplayFieldView();
	void SetDisplayFieldView(BOOL bNewValue);
	BOOL GetDisplayToolbar();
	void SetDisplayToolbar(BOOL bNewValue);
	BOOL GetUseIndexForSpeed();
	void SetUseIndexForSpeed(BOOL bNewValue);
	BOOL GetTranslateDosStrings();
	void SetTranslateDosStrings(BOOL bNewValue);
	BOOL GetTranslateDosMemos();
	void SetTranslateDosMemos(BOOL bNewValue);
	long GetConvertDateTimeType();
	void SetConvertDateTimeType(long nNewValue);
	BOOL GetConvertNullFieldToDefault();
	void SetConvertNullFieldToDefault(BOOL bNewValue);
	BOOL GetCaseInsensitiveSQLData();
	void SetCaseInsensitiveSQLData(BOOL bNewValue);
	BOOL GetVerifyOnEveryPrint();
	void SetVerifyOnEveryPrint(BOOL bNewValue);
	BOOL GetDisplayRulers();
	void SetDisplayRulers(BOOL bNewValue);
	BOOL GetEnableSnapToGrid();
	void SetEnableSnapToGrid(BOOL bNewValue);
	BOOL GetDisplayGrid();
	void SetDisplayGrid(BOOL bNewValue);
	float GetGridSize();
	void SetGridSize(float newValue);
	void SaveReport(LPCTSTR reportName);
	BOOL GetDisplayHiddenSections();
	void SetDisplayHiddenSections(BOOL bNewValue);
	LPUNKNOWN GetReportObject();
	void SetReportObject(LPUNKNOWN newValue);
	BOOL GetEnableHelp();
	void SetEnableHelp(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CRDESIGNERCTRL_H__A0C0F2A3_FBEE_4C37_9F4B_306B119F2153__INCLUDED_)
