// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "crystalreportviewer4.h"

// Dispatch interfaces referenced by this interface
#include "crvtrackcursorinfo.h"

/////////////////////////////////////////////////////////////////////////////
// CCrystalReportViewer4

IMPLEMENT_DYNCREATE(CCrystalReportViewer4, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCrystalReportViewer4 properties

/////////////////////////////////////////////////////////////////////////////
// CCrystalReportViewer4 operations

LPUNKNOWN CCrystalReportViewer4::GetReportSource()
{
	LPUNKNOWN result;
	InvokeHelper(0xfa, DISPATCH_PROPERTYGET, VT_UNKNOWN, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetReportSource(LPUNKNOWN newValue)
{
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0xfa, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

BOOL CCrystalReportViewer4::GetDisplayGroupTree()
{
	BOOL result;
	InvokeHelper(0xfb, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetDisplayGroupTree(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfb, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetDisplayToolbar()
{
	BOOL result;
	InvokeHelper(0xfc, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetDisplayToolbar(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfc, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableGroupTree()
{
	BOOL result;
	InvokeHelper(0xfd, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableGroupTree(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfd, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableNavigationControls()
{
	BOOL result;
	InvokeHelper(0xfe, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableNavigationControls(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfe, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableStopButton()
{
	BOOL result;
	InvokeHelper(0xff, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableStopButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xff, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnablePrintButton()
{
	BOOL result;
	InvokeHelper(0x100, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnablePrintButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x100, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableZoomControl()
{
	BOOL result;
	InvokeHelper(0x101, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableZoomControl(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x101, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableCloseButton()
{
	BOOL result;
	InvokeHelper(0x102, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableCloseButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x102, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableProgressControl()
{
	BOOL result;
	InvokeHelper(0x103, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableProgressControl(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x103, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableSearchControl()
{
	BOOL result;
	InvokeHelper(0x104, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableSearchControl(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x104, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableRefreshButton()
{
	BOOL result;
	InvokeHelper(0x105, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableRefreshButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x105, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableDrillDown()
{
	BOOL result;
	InvokeHelper(0x106, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableDrillDown(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x106, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableAnimationCtrl()
{
	BOOL result;
	InvokeHelper(0x107, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableAnimationCtrl(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x107, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableSelectExpertButton()
{
	BOOL result;
	InvokeHelper(0x108, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableSelectExpertButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x108, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

void CCrystalReportViewer4::ViewReport()
{
	InvokeHelper(0x109, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CCrystalReportViewer4::GetEnableToolbar()
{
	BOOL result;
	InvokeHelper(0x154, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableToolbar(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x154, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetDisplayBorder()
{
	BOOL result;
	InvokeHelper(0x155, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetDisplayBorder(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x155, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetDisplayTabs()
{
	BOOL result;
	InvokeHelper(0x156, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetDisplayTabs(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x156, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetDisplayBackgroundEdge()
{
	BOOL result;
	InvokeHelper(0x157, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetDisplayBackgroundEdge(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x157, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CCRVTrackCursorInfo CCrystalReportViewer4::GetTrackCursorInfo()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x159, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CCRVTrackCursorInfo(pDispatch);
}

short CCrystalReportViewer4::GetActiveViewIndex()
{
	short result;
	InvokeHelper(0x15a, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

short CCrystalReportViewer4::GetViewCount()
{
	short result;
	InvokeHelper(0x15b, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::ActivateView(const VARIANT& Index)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x15c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Index);
}

void CCrystalReportViewer4::AddView(const VARIANT& GroupPath)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x15d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &GroupPath);
}

void CCrystalReportViewer4::CloseView(const VARIANT& Index)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x15e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Index);
}

VARIANT CCrystalReportViewer4::GetViewPath(short Index)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x15f, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		Index);
	return result;
}

void CCrystalReportViewer4::PrintReport()
{
	InvokeHelper(0x160, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer4::Refresh()
{
	InvokeHelper(0x161, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer4::SearchForText(LPCTSTR Text)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x162, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Text);
}

void CCrystalReportViewer4::ShowFirstPage()
{
	InvokeHelper(0x163, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer4::ShowNextPage()
{
	InvokeHelper(0x164, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer4::ShowPreviousPage()
{
	InvokeHelper(0x165, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer4::ShowLastPage()
{
	InvokeHelper(0x166, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer4::ShowNthPage(short PageNumber)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x167, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PageNumber);
}

void CCrystalReportViewer4::Zoom(short ZoomLevel)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x168, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ZoomLevel);
}

long CCrystalReportViewer4::GetCurrentPageNumber()
{
	long result;
	InvokeHelper(0x169, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::ShowGroup(const VARIANT& GroupPath)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x16a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &GroupPath);
}

BOOL CCrystalReportViewer4::GetIsBusy()
{
	BOOL result;
	InvokeHelper(0x16b, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CCrystalReportViewer4::GetEnablePopupMenu()
{
	BOOL result;
	InvokeHelper(0x16c, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnablePopupMenu(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x16c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableExportButton()
{
	BOOL result;
	InvokeHelper(0x16d, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableExportButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x16d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer4::GetEnableSearchExpertButton()
{
	BOOL result;
	InvokeHelper(0x16f, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableSearchExpertButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x16f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

void CCrystalReportViewer4::SearchByFormula(LPCTSTR formula)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x170, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 formula);
}

CString CCrystalReportViewer4::GetViewName(BSTR* pTabName)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x171, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		pTabName);
	return result;
}

BOOL CCrystalReportViewer4::GetEnableHelpButton()
{
	BOOL result;
	InvokeHelper(0x172, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::SetEnableHelpButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x172, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

VARIANT CCrystalReportViewer4::GetGroup()
{
	VARIANT result;
	InvokeHelper(0x190, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer4::GetLastPageNumber(long* pageN, BOOL* lastPageKnown)
{
	static BYTE parms[] =
		VTS_PI4 VTS_PBOOL;
	InvokeHelper(0x191, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pageN, lastPageKnown);
}

void CCrystalReportViewer4::RefreshEx(BOOL refreshServerData)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x192, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 refreshServerData);
}
